var group___s_m_a_r_t_c_a_r_d___exported___constants =
[
    [ "SMARTCARD Error", "group___s_m_a_r_t_c_a_r_d___error.html", "group___s_m_a_r_t_c_a_r_d___error" ],
    [ "SMARTCARD Word Length", "group___s_m_a_r_t_c_a_r_d___word___length.html", "group___s_m_a_r_t_c_a_r_d___word___length" ],
    [ "SMARTCARD Number of Stop Bits", "group___s_m_a_r_t_c_a_r_d___stop___bits.html", "group___s_m_a_r_t_c_a_r_d___stop___bits" ],
    [ "SMARTCARD Parity", "group___s_m_a_r_t_c_a_r_d___parity.html", "group___s_m_a_r_t_c_a_r_d___parity" ],
    [ "SMARTCARD Transfer Mode", "group___s_m_a_r_t_c_a_r_d___mode.html", "group___s_m_a_r_t_c_a_r_d___mode" ],
    [ "SMARTCARD Clock Polarity", "group___s_m_a_r_t_c_a_r_d___clock___polarity.html", "group___s_m_a_r_t_c_a_r_d___clock___polarity" ],
    [ "SMARTCARD Clock Phase", "group___s_m_a_r_t_c_a_r_d___clock___phase.html", "group___s_m_a_r_t_c_a_r_d___clock___phase" ],
    [ "SMARTCARD Last Bit", "group___s_m_a_r_t_c_a_r_d___last___bit.html", "group___s_m_a_r_t_c_a_r_d___last___bit" ],
    [ "SMARTCARD One Bit Sampling Method", "group___s_m_a_r_t_c_a_r_d___one_bit___sampling.html", "group___s_m_a_r_t_c_a_r_d___one_bit___sampling" ],
    [ "SMARTCARD NACK Enable", "group___s_m_a_r_t_c_a_r_d___n_a_c_k___enable.html", "group___s_m_a_r_t_c_a_r_d___n_a_c_k___enable" ],
    [ "SMARTCARD Timeout Enable", "group___s_m_a_r_t_c_a_r_d___timeout___enable.html", "group___s_m_a_r_t_c_a_r_d___timeout___enable" ],
    [ "SMARTCARD advanced feature initialization type", "group___s_m_a_r_t_c_a_r_d___advanced___features___initialization___type.html", "group___s_m_a_r_t_c_a_r_d___advanced___features___initialization___type" ],
    [ "SMARTCARD advanced feature TX pin active level inversion", "group___s_m_a_r_t_c_a_r_d___tx___inv.html", "group___s_m_a_r_t_c_a_r_d___tx___inv" ],
    [ "SMARTCARD advanced feature RX pin active level inversion", "group___s_m_a_r_t_c_a_r_d___rx___inv.html", "group___s_m_a_r_t_c_a_r_d___rx___inv" ],
    [ "SMARTCARD advanced feature Binary Data inversion", "group___s_m_a_r_t_c_a_r_d___data___inv.html", "group___s_m_a_r_t_c_a_r_d___data___inv" ],
    [ "SMARTCARD advanced feature RX TX pins swap", "group___s_m_a_r_t_c_a_r_d___rx___tx___swap.html", "group___s_m_a_r_t_c_a_r_d___rx___tx___swap" ],
    [ "SMARTCARD advanced feature Overrun Disable", "group___s_m_a_r_t_c_a_r_d___overrun___disable.html", "group___s_m_a_r_t_c_a_r_d___overrun___disable" ],
    [ "SMARTCARD advanced feature DMA Disable on Rx Error", "group___s_m_a_r_t_c_a_r_d___d_m_a___disable__on___rx___error.html", "group___s_m_a_r_t_c_a_r_d___d_m_a___disable__on___rx___error" ],
    [ "SMARTCARD advanced feature MSB first", "group___s_m_a_r_t_c_a_r_d___m_s_b___first.html", "group___s_m_a_r_t_c_a_r_d___m_s_b___first" ],
    [ "SMARTCARD Flags", "group___s_m_a_r_t_c_a_r_d___flags.html", "group___s_m_a_r_t_c_a_r_d___flags" ],
    [ "SMARTCARD Interrupts Definition", "group___s_m_a_r_t_c_a_r_d___interrupt__definition.html", "group___s_m_a_r_t_c_a_r_d___interrupt__definition" ],
    [ "SMARTCARD Interruption Clear Flags", "group___s_m_a_r_t_c_a_r_d___i_t___c_l_e_a_r___flags.html", "group___s_m_a_r_t_c_a_r_d___i_t___c_l_e_a_r___flags" ],
    [ "SMARTCARD auto retry counter LSB position in CR3 register", "group___s_m_a_r_t_c_a_r_d___c_r3___s_c_a_r_c_n_t___l_s_b___p_o_s.html", "group___s_m_a_r_t_c_a_r_d___c_r3___s_c_a_r_c_n_t___l_s_b___p_o_s" ],
    [ "SMARTCARD guard time value LSB position in GTPR register", "group___s_m_a_r_t_c_a_r_d___g_t_p_r___g_t___l_s_b___p_o_s.html", "group___s_m_a_r_t_c_a_r_d___g_t_p_r___g_t___l_s_b___p_o_s" ],
    [ "SMARTCARD block length LSB position in RTOR register", "group___s_m_a_r_t_c_a_r_d___r_t_o_r___b_l_e_n___l_s_b___p_o_s.html", "group___s_m_a_r_t_c_a_r_d___r_t_o_r___b_l_e_n___l_s_b___p_o_s" ],
    [ "SMARTCARD interruptions flags mask", "group___s_m_a_r_t_c_a_r_d___interruption___mask.html", "group___s_m_a_r_t_c_a_r_d___interruption___mask" ],
    [ "SMARTCARD Request Parameters", "group___s_m_a_r_t_c_a_r_d___request___parameters.html", "group___s_m_a_r_t_c_a_r_d___request___parameters" ]
];